[package]
name = "backend"
version = "0.1.0"
authors = ["happysalada <raphael@megzari.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
env_logger = "0.8.4"
juniper = "0.15.6"
lazy_static = "1.4.0"
log = "0.4.14"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.5", features = ["sqlite", "runtime-tokio-native-tls", "macros", "migrate"] }
tokio = "1.8.0"
trillium = "0.1.3"
trillium-logger = "0.1.2"
trillium-router = "0.1.1"
trillium-testing = "0.1.0"
trillium-tokio = "0.1.2"
ulid = { version = "0.4.1", features = ["serde"] }
